## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [1]:
import torch
import torch.nn as nn
from collections import OrderedDict
import torch.optim as optim
import matplotlib.pyplot as plt


In [2]:
# your code here
#model1 = nn.Sequential(OrderedDict([
#    ('hidden', nn.
#]))
model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 2)),
    ('sigmoid', nn.Sigmoid()),
    ('output', nn.Linear(2, 2)),
    ('sigmoid', nn.Sigmoid())
]))

model2 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 4)),
    ('sigmoid', nn.Sigmoid()),
    ('output', nn.Linear(4, 2)),
    ('sigmoid', nn.Sigmoid())
]))

model3 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 8)),
    ('sigmoid', nn.Sigmoid()),
    ('output', nn.Linear(8, 2)),
    ('sigmoid', nn.Sigmoid())
]))

# the database contains 0 and 1 as we have to add 2 bits
# 3 layers : input layer, hidden layer and output layer
# each layer contains 2 neurons
# sigmoid function is the used activation function

# for model1
# input layer has 2 neurons, hidden layer has 2 neurons and output layer has 2 neurons

# for model2
# input layer has 2 neurons, hidden layer has 4 neurons and output layer has 2 neurons

# for model3
# input layer has 2 neurons, hidden layer has 8 neurons and output layer has 2 neurons

In [3]:
print(model1)
print(model2)
print(model3)

Sequential(
  (hidden): Linear(in_features=2, out_features=2, bias=True)
  (sigmoid): Sigmoid()
  (output): Linear(in_features=2, out_features=2, bias=True)
)
Sequential(
  (hidden): Linear(in_features=2, out_features=4, bias=True)
  (sigmoid): Sigmoid()
  (output): Linear(in_features=4, out_features=2, bias=True)
)
Sequential(
  (hidden): Linear(in_features=2, out_features=8, bias=True)
  (sigmoid): Sigmoid()
  (output): Linear(in_features=8, out_features=2, bias=True)
)


In [4]:
# your code here
#data_in = torch.tensor( ...

# Create a tensor containing all possible 2-bit input combinations
data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)

print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [5]:
# your code here
# data_target = torch.tensor( ...


# Create a tensor containing the target output for each input combination
data_target = torch.tensor([[0,  0], [0, 1], [0, 1], [1, 0]], dtype=torch.float32)

print(data_target)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [22]:
# your code here
# criterion = 
# optimizer = 

# Define the binary cross-entropy loss function
criterion = nn.BCEWithLogitsLoss()

# Define the Adam optimizer with a learning rate of 0.1
optimizer1 = optim.SGD(model1.parameters(), lr=0.1)
optimizer2 = optim.SGD(model2.parameters(), lr=0.1)
optimizer3 = optim.SGD(model3.parameters(), lr=0.1)

In [23]:
# your code here
# Train the model

# Train the model for 1000 epochs
num_epochs = 1000

print('MODEL 1')
for epoch in range(num_epochs):
    # Forward pass
    output = model1(data_in)
    
    # Calculate the loss
    loss = criterion(output, data_target)
    
    # Backward pass and optimization
    optimizer1.zero_grad()
    loss.backward()
    optimizer1.step()
    
    # Print the loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")
print('\n')
        
print('MODEL 2')
for epoch in range(num_epochs):
    # Forward pass
    output = model2(data_in)
    
    # Calculate the loss
    loss = criterion(output, data_target)
    
    # Backward pass and optimization
    optimizer2.zero_grad()
    loss.backward()
    optimizer2.step()
    
    # Print the loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")
print('\n')        
        
print('MODEL 3')
for epoch in range(num_epochs):
    # Forward pass
    output = model3(data_in)
    
    # Calculate the loss
    loss = criterion(output, data_target)
    
    # Backward pass and optimization
    optimizer3.zero_grad()
    loss.backward()
    optimizer3.step()
    
    # Print the loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

MODEL 1
Epoch [100/1000], Loss: 0.4582
Epoch [200/1000], Loss: 0.4497
Epoch [300/1000], Loss: 0.4416
Epoch [400/1000], Loss: 0.4339
Epoch [500/1000], Loss: 0.4266
Epoch [600/1000], Loss: 0.4198
Epoch [700/1000], Loss: 0.4134
Epoch [800/1000], Loss: 0.4074
Epoch [900/1000], Loss: 0.4017
Epoch [1000/1000], Loss: 0.3964


MODEL 2
Epoch [100/1000], Loss: 0.3591
Epoch [200/1000], Loss: 0.3507
Epoch [300/1000], Loss: 0.3415
Epoch [400/1000], Loss: 0.3313
Epoch [500/1000], Loss: 0.3202
Epoch [600/1000], Loss: 0.3082
Epoch [700/1000], Loss: 0.2954
Epoch [800/1000], Loss: 0.2820
Epoch [900/1000], Loss: 0.2681
Epoch [1000/1000], Loss: 0.2538


MODEL 3
Epoch [100/1000], Loss: 0.3796
Epoch [200/1000], Loss: 0.3756
Epoch [300/1000], Loss: 0.3713
Epoch [400/1000], Loss: 0.3667
Epoch [500/1000], Loss: 0.3616
Epoch [600/1000], Loss: 0.3559
Epoch [700/1000], Loss: 0.3494
Epoch [800/1000], Loss: 0.3421
Epoch [900/1000], Loss: 0.3339
Epoch [1000/1000], Loss: 0.3250


In [28]:
# your code here
# visualize the resuts

output1 = model1(data_in)

# Convert the output probabilities to binary predictions
predictions = (output1 >= 0.5).float()

# Print the model's predictions
print("Model1's predictions:")
print(predictions)

output1 = model2(data_in)

# Convert the output probabilities to binary predictions
predictions = (output1 >= 0.5).float()

# Print the model's predictions
print("Model2's predictions:")
print(predictions)


output1 = model3(data_in)

# Convert the output probabilities to binary predictions
predictions = (output1 >= 0.5).float()

# Print the model's predictions
print("Model3's predictions:")
print(predictions)

Model1's predictions:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.]])
Model2's predictions:
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Model3's predictions:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.]])


In [30]:
# your code here
# print model wights

accuracies = []
models = [model1, model2, model3]
for model in models:
    model.eval()
#with torch.no_grad():
    outputs = model(data_in)
    predicted = (outputs >= 0.5).float()
    accuracy = (predicted == data_target).float().mean()
    accuracies.append(accuracy)

    print("Accuracy: {:.2f}%".format(accuracy.item() * 100))

print('\n')
    
# Select the best-performing model
best_model = models[accuracies.index(max(accuracies))]


print('Model ' + str(accuracies.index(max(accuracies)) + 1) + ' is the best!')

print('\n')

# Display the weights of each layer in the selected model
for name, param in best_model.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Accuracy: 75.00%
Accuracy: 100.00%
Accuracy: 75.00%


Model 2 is the best!


hidden.weight tensor([[-2.5194, -2.5022],
        [-1.2399, -1.7273],
        [-2.9751, -2.6053],
        [ 1.3578,  2.0023]])
hidden.bias tensor([ 0.7005,  0.1221,  4.1706, -2.1453])
output.weight tensor([[-2.7793, -1.8374, -5.6114,  3.9682],
        [-2.4704, -1.1525,  2.0726, -0.7463]])
output.bias tensor([ 0.4617, -0.2094])
